### ISSUE TITLE
Chapter 20 api metric script name differs from book in AWS

### ISSUE THREAD

**Issue by RubenMakandra** [book-of-kubernetes/examples#22]
Chapter 20 has the command `/opt/api-server-metrics.sh` to execute the script. In the AWS Environment the file is named `api-metrics.sh`.

**Comment by AlanHohn** [comment]
Thanks for the find! I've updated the examples so that either name works for now and we'll get it fixed in any future print copies. (If you have an existing environment, just re-run the Ansible playbook.yaml after pulling the latest code.)

If you're curious, the reason for the error is that I needed a shorter script name so the name would fit into the margin, but I forgot to fix the copy / pasted example 😖
